// =============================================================================
// -                     Модуль локализации строковых ресурсов                 -
// -                                                                           -
// =============================================================================
// - Последнее изменение: 27.12.2019   By S.Bortsov                            -
// =============================================================================
unit uControlsLocalization;

interface

uses  cxClasses,
      cxDataConsts,
      cxPivotGridStrs,
      cxEditConsts,
      cxExtEditConsts,
      cxFilterConsts,
      cxGridPopupMenuConsts,
      dxDockConsts,
      cxGridStrs,
      cxPivotGrid,
      dxPSRes,
      cxPCConsts,
      cxExportStrs,
      cxFilterControlStrs,
      dxNavBarConsts,
      cxLibraryStrs,
      dxBarDBNavStrs,
      dxBarStrs,
      dxThemeConsts,
      cxVGridConsts,
      cxSchedulerStrs,
      dxCore;

implementation

initialization


 cxSetResourceString(@scxTime2w,      '2 недели');
 cxSetResourceString(@cxSDateNow, 'сейчас');
 cxSetResourceString(@cxSDatePopupClear, 'Очистить');
 cxSetResourceString(@cxSDatePopupNow, 'Сейчас');
 cxSetResourceString(@cxSDatePopupToday, 'Сегодня');
 cxSetResourceString(@cxSDateToday, 'сегодня');
 cxSetResourceString(@cxSDateTomorrow, 'завтра');
 cxSetResourceString(@cxSDateYesterday, 'вчера');
 cxSetResourceString(@cxSEditValueOutOfBounds, 'Значение за пределами допустимого');
 cxSetResourceString(@cxSFilterAddCondition, 'Добавить &Condition');
 cxSetResourceString(@cxSFilterAddGroup, 'Добавить &Group');
 cxSetResourceString(@cxSFilterAndCaption, 'И');
 cxSetResourceString(@cxSFilterBlankCaption, 'пустое');
 cxSetResourceString(@cxSFilterBoolOperatorAnd, 'И');
 cxSetResourceString(@cxSFilterBoolOperatorNotAnd, 'НЕ И');
 cxSetResourceString(@cxSFilterBoolOperatorNotOr, 'НЕ ИЛИ');
 cxSetResourceString(@cxSFilterBoolOperatorOr, 'ИЛИ');
 cxSetResourceString(@cxSFilterBoxAllCaption, '(Все)');
 cxSetResourceString(@cxSFilterBoxBlanksCaption, '(Пустые)');
 cxSetResourceString(@cxSFilterBoxCustomCaption, '(Настроить...)');
 cxSetResourceString(@cxSFilterBoxNonBlanksCaption, '(Непустые)');
 cxSetResourceString(@cxSFilterClearAll, 'Очистить &All');
 cxSetResourceString(@cxSFilterControlDialogActionCancelCaption, 'Отмена');
 cxSetResourceString(@cxSFilterControlDialogCaption, 'Построитель фильтра');
 cxSetResourceString(@cxSFilterControlDialogOpenDialogCaption, 'Открыть существующий фильтр');
 cxSetResourceString(@cxSFilterControlDialogSaveDialogCaption, 'Сохранить текущие настройки фильтра в файл');
 cxSetResourceString(@cxSFilterControlNullString, '<пусто>');
 cxSetResourceString(@cxSFilterDialogCaption, 'Настройка фильтра');
 cxSetResourceString(@cxSFilterDialogCharactersSeries, 'для представления любой последовательности символов');
 cxSetResourceString(@cxSFilterDialogInvalidValue, 'Некорректное значение');
 cxSetResourceString(@cxSFilterDialogOperationAnd, 'И');
 cxSetResourceString(@cxSFilterDialogOperationOr, 'ИЛИ');
 cxSetResourceString(@cxSFilterDialogRows, 'Показывать только строки, в которых:');
 cxSetResourceString(@cxSFilterDialogSingleCharacter, 'для представления любого единичного символа');
 cxSetResourceString(@cxSFilterDialogUse, 'Использовать');
 cxSetResourceString(@cxSFilterErrorBuilding, 'Невозможно построить фильтр из источника ');
 cxSetResourceString(@cxSFilterFooterAddCondition, 'нажать кнопку для добавления нового условия');
 cxSetResourceString(@cxSFilterGroupCaption, 'применяется для следующих условий');
 cxSetResourceString(@cxSFilterNotCaption, 'НЕ');
 cxSetResourceString(@cxSFilterOperatorBeginsWith, 'начинается с');
 cxSetResourceString(@cxSFilterOperatorBetween, 'между');
 cxSetResourceString(@cxSFilterOperatorContains, 'содержит');
 cxSetResourceString(@cxSFilterOperatorDoesNotBeginWith, 'не начинается с ');
 cxSetResourceString(@cxSFilterOperatorDoesNotContain, 'не содержит');
 cxSetResourceString(@cxSFilterOperatorDoesNotEndWith, 'не заканчивается на');
 cxSetResourceString(@cxSFilterOperatorEndsWith, 'заканчивается на');
 cxSetResourceString(@cxSFilterOperatorEqual, 'равно');
 cxSetResourceString(@cxSFilterOperatorFuture, 'в будущем');
 cxSetResourceString(@cxSFilterOperatorGreater, 'больше чем');
 cxSetResourceString(@cxSFilterOperatorGreaterEqual, 'больше или равно');
 cxSetResourceString(@cxSFilterOperatorInList, 'внутри');
 cxSetResourceString(@cxSFilterOperatorIsNotNull, 'не пустое');
 cxSetResourceString(@cxSFilterOperatorIsNull, 'пустое');
 cxSetResourceString(@cxSFilterOperatorLast14Days, 'за последние 14 дней');
 cxSetResourceString(@cxSFilterOperatorLast30Days, 'за последние 30 дней');
 cxSetResourceString(@cxSFilterOperatorLast7Days, 'за последние 7 дней');
 cxSetResourceString(@cxSFilterOperatorLastMonth, 'за последний месяц');
 cxSetResourceString(@cxSFilterOperatorLastTwoWeeks, 'за оследние 2 недели');
 cxSetResourceString(@cxSFilterOperatorLastWeek, 'за последнюю неделю');
 cxSetResourceString(@cxSFilterOperatorLastYear, 'за прошедший год');
 cxSetResourceString(@cxSFilterOperatorLess, 'меньше');
 cxSetResourceString(@cxSFilterOperatorLessEqual, 'меньше или равен');
 cxSetResourceString(@cxSFilterOperatorLike, 'содержит');
 cxSetResourceString(@cxSFilterOperatorNext14Days, 'следующие 14 дней');
 cxSetResourceString(@cxSFilterOperatorNext30Days, 'следующие 30 дней');
 cxSetResourceString(@cxSFilterOperatorNext7Days, 'следующие 7 дней');
 cxSetResourceString(@cxSFilterOperatorNextMonth, 'следующий месяц');
 cxSetResourceString(@cxSFilterOperatorNextTwoWeeks, 'следующие 2 недели');
 cxSetResourceString(@cxSFilterOperatorNextWeek, 'следующая неделя');
 cxSetResourceString(@cxSFilterOperatorNextYear, 'следующий год');
 cxSetResourceString(@cxSFilterOperatorNotBetween, 'не между');
 cxSetResourceString(@cxSFilterOperatorNotEqual, 'не равно');
 cxSetResourceString(@cxSFilterOperatorNotInList, 'не внутри');
 cxSetResourceString(@cxSFilterOperatorNotLike, 'не содержит');
 cxSetResourceString(@cxSFilterOperatorPast, 'в прошлом');
 cxSetResourceString(@cxSFilterOperatorThisMonth, 'в этом месяце');
 cxSetResourceString(@cxSFilterOperatorThisWeek, 'на этой неделе');
 cxSetResourceString(@cxSFilterOperatorThisYear, 'в этом году');
 cxSetResourceString(@cxSFilterOperatorToday, 'сегодня');
 cxSetResourceString(@cxSFilterOperatorTomorrow, 'завтра');
 cxSetResourceString(@cxSFilterOperatorYesterday, 'вчера');
 cxSetResourceString(@cxSFilterOrCaption, 'ИЛИ');
 cxSetResourceString(@cxSFilterRootButtonCaption, 'Фильтр');
 cxSetResourceString(@dxSBAR_ADDEX, 'Добавить...');
 cxSetResourceString(@dxSBAR_ADDREMOVEBUTTONS, '&Добавить/Удалить кнопки');
 cxSetResourceString(@dxSBAR_CANCEL, 'Отменить');
 cxSetResourceString(@dxSBAR_CAPTION, 'Настройка');
 cxSetResourceString(@dxSBAR_CATEGORIES, 'Категории:');
 cxSetResourceString(@dxSBAR_CATEGORYADD, 'Добавить категорию');
 cxSetResourceString(@dxSBAR_CATEGORYINSERT, 'Вставить категорию');
 cxSetResourceString(@dxSBAR_CATEGORYNAME, 'Наименование категории:');
 cxSetResourceString(@dxSBAR_CATEGORYRENAME, 'Переименовать категорию');
 cxSetResourceString(@dxSBAR_CLEAR, 'Очистить');
 cxSetResourceString(@dxSBAR_CLOSE, 'Закрыть');
 cxSetResourceString(@dxSBAR_COLORAUTOTEXT, '(автоматически)');
 cxSetResourceString(@dxSBAR_COMMANDS, 'Команды:');
 cxSetResourceString(@dxSBAR_CP_ADDBUTTON, 'Добавить кнопку');
 cxSetResourceString(@dxSBAR_CP_ADDCXITEM, 'Добавить &cxEditItem');
 cxSetResourceString(@dxSBAR_CP_ADDDXITEM, 'Добавить элемент');
 cxSetResourceString(@dxSBAR_CP_ADDSEPARATOR, 'Добавить разделитель');
 cxSetResourceString(@dxSBAR_CP_ALLVIEWLEVELS, 'Все');
 cxSetResourceString(@dxSBAR_CP_DELETE, 'Удалить');
 cxSetResourceString(@dxSBAR_CP_DELETEITEM, 'Удалить элемент');
 cxSetResourceString(@dxSBAR_CP_DELETELINK, 'Удалить ссылку');
 cxSetResourceString(@dxSBAR_CP_RESET, 'Сбросить');
 cxSetResourceString(@dxSBAR_CUSTOMIZE, '&Настроить...');
 cxSetResourceString(@dxSBAR_DATECLEAR, 'Очистить');
 cxSetResourceString(@dxSBAR_DELETE, 'Удалить');
 cxSetResourceString(@dxSBAR_DESCRIPTION, 'Описание');
 cxSetResourceString(@dxSBAR_DIALOGCANCEL, 'Отменить');
 cxSetResourceString(@dxSBAR_HINTOPT1, 'Показывать подсказки на панелях');
 cxSetResourceString(@dxSBAR_HINTOPT2, 'Показывать горячие клавиши в подсказках');
 cxSetResourceString(@dxSBAR_INSERTEX, 'Вставить...');
 cxSetResourceString(@dxSBAR_LARGEICONS, '&Большие значки');
 cxSetResourceString(@dxSBAR_LOOKUPDIALOGCANCEL, 'Отменить');
 cxSetResourceString(@dxSBAR_MENUANIMATIONS, 'Анимация меню:');
 cxSetResourceString(@dxSBAR_MENUSSHOWRECENTITEMS, 'Первыми в меню показываются недавние команды');
 cxSetResourceString(@dxSBAR_MODIFY, '... изменить');
 cxSetResourceString(@dxSBAR_NEWBUTTONCAPTION, 'Новая кнопка');
 cxSetResourceString(@dxSBAR_OTHEROPTIONS, 'Другие');
 cxSetResourceString(@dxSBAR_PERSMENUSANDTOOLBARS, 'Меню и Панели инструментов');
 cxSetResourceString(@dxSBAR_RENAMEEX, 'Переименовать...');
 cxSetResourceString(@dxSBAR_RESETTOOLBAR, 'Сбросить настройки панели');
 cxSetResourceString(@dxSBAR_RESETUSAGEDATA, '&Сбросить мои настройки');
 cxSetResourceString(@dxSBAR_SHOWFULLMENUSAFTERDELAY, 'Показывать полное меню после короткой задержки');
 cxSetResourceString(@dxSBAR_TABSHEET1, 'Панели');
 cxSetResourceString(@dxSBAR_TABSHEET2, 'Команды');
 cxSetResourceString(@dxSBAR_TABSHEET3, 'Опции');
 cxSetResourceString(@dxSBAR_TDELETE, '&Удалить');
 cxSetResourceString(@dxSBAR_TNEW, '&Новая панель...');
 cxSetResourceString(@dxSBAR_TOOLBAREXISTS, 'Панель с названием ''%s'' уже существует. Введите другое название.');
 cxSetResourceString(@dxSBAR_TOOLBARNEWNAME, 'Настраиваемая панель');
 cxSetResourceString(@dxSBAR_TOOLBARS, 'Панели:');
 cxSetResourceString(@dxSBAR_TRENAME, 'Переименовать...');
 cxSetResourceString(@dxSBAR_TRESET, 'Сбросить...');
 cxSetResourceString(@dxSBAR_WANTTOCLEARCOMMANDS, 'Вы уверены, что хотите удалить все команды в категории ''%s'' ?');
 cxSetResourceString(@dxSBAR_WANTTODELETECATEGORY, 'Вы уверены, что хотите удалить категорию ''%s'' ?');
 cxSetResourceString(@dxSBAR_WANTTODELETETOOLBAR, 'Вы уверены, что хотите удалить панель ''%s''?');
 cxSetResourceString(@dxSBAR_WANTTODELETETOOLBARS, 'Вы уверены, что хотите удалить выбраную панель?');
 cxSetResourceString(@dxSBAR_WANTTORESETTOOLBAR, 'Вы уверены, что хотите сбросить все изменения для панели ''%s'' ?');
 cxSetResourceString(@dxSBAR_WANTTORESETUSAGEDATA, 'Будут удалены все изменения в командах, которые вы сделали и восстановлены все установки по умолчанию для меню и панелей. Вы хотите продолжить?');
 cxSetResourceString(@scxGridBandsQuickCustomizationHint, 'Щелкните сюда чтобы показать/скрыть/сдвинуть диапазоны');
 cxSetResourceString(@scxGridChartAlignment, 'Выравнивание');
 cxSetResourceString(@scxGridChartAlignmentCenter, 'По центру');
 cxSetResourceString(@scxGridChartAlignmentDefault, 'По умолчанию');
 cxSetResourceString(@scxGridChartAlignmentEnd, 'Конец');
 cxSetResourceString(@scxGridChartAlignmentStart, 'Начало');
 cxSetResourceString(@scxGridChartBorder, 'Граница');
 cxSetResourceString(@scxGridChartCategoriesDisplayText, 'Данные');
 cxSetResourceString(@scxGridChartCustomizationFormDataGroupsPageCaption, 'Группы данных');
 cxSetResourceString(@scxGridChartCustomizationFormSortBySeries, 'Сортировать по:');
 cxSetResourceString(@scxGridChartLegend, 'Легенда');
 cxSetResourceString(@scxGridChartOrientationHorizontal, 'Горизонтальн.');
 cxSetResourceString(@scxGridChartOrientationVertical, 'Вертикальн.');
 cxSetResourceString(@scxGridChartOther, 'Другое');
 cxSetResourceString(@scxGridChartPositionBottom, 'Низ');
 cxSetResourceString(@scxGridChartPositionTop, 'Верх');
 cxSetResourceString(@scxGridColumnsQuickCustomizationHint, 'Нажмите здесь чтобы показать/скрыть/переместить столбцы');
 cxSetResourceString(@scxGridConverterNotExistComponent, 'Компонент не существует');
 cxSetResourceString(@scxGridCustomizationFormBandsPageCaption, 'Диапазоны');
 cxSetResourceString(@scxGridCustomizationFormCaption, 'Настройка вида таблицы');
 cxSetResourceString(@scxGridCustomizationFormColumnsPageCaption, 'Колонки');
 cxSetResourceString(@scxGridCustomizationFormRowsPageCaption, 'Строки');
 cxSetResourceString(@scxGridDeletingFocusedConfirmationText, 'Удалить запись?');
 cxSetResourceString(@scxGridDeletingSelectedConfirmationText, 'Удалить все выбранные записи?');
 cxSetResourceString(@scxGridFilterApplyButtonCaption, 'Применить фильтр');
 cxSetResourceString(@scxGridFilterCustomizeButtonCaption, 'Настроить...');
 cxSetResourceString(@scxGridFilterIsEmpty, '<Фильтр пуст>');
 cxSetResourceString(@scxGridFilterRowInfoText, 'Нажмите сюда, чтобы задать фильтр');
 cxSetResourceString(@scxGridGroupByBoxCaption, 'Перетяните сюда заголовок колонки, чтобы выполнить группировку по ней ');
 cxSetResourceString(@scxGridNewItemRowInfoText, 'Нажмите сюда чтобы добавить новую строку');
 cxSetResourceString(@scxGridNoDataInfoText, '<Не найдено данных для отображения>');
 cxSetResourceString(@scxNoDataToDisplay, '<Нет данных>');
 cxSetResourceString(@scxPCDefaultHintCloseButton, 'Закрыть активное окно');
 cxSetResourceString(@scxPCDefaultHintTabCloseButton, 'Закрыть окно');
 cxSetResourceString(@sdxAddReport, 'Добавить отчет');
 cxSetResourceString(@sdxAddressCaption, 'Адрес');
 cxSetResourceString(@sdxAlignment, 'Выравнивание');
 cxSetResourceString(@sdxBackground, '&Фон');
 cxSetResourceString(@sdxBands, '&Диапазоны');
 cxSetResourceString(@sdxBorderColor, '&Цвет границы:');
 cxSetResourceString(@sdxBorderLines, '&Граница');
 cxSetResourceString(@sdxBottom, '&Снизу:');
 cxSetResourceString(@sdxBtnAdd, 'Добавить');
 cxSetResourceString(@sdxBtnApply, '&AПрименить');
 cxSetResourceString(@sdxBtnBackground, 'Цвет фона');
 cxSetResourceString(@sdxBtnBrowse, '&Найти...');
 cxSetResourceString(@sdxBtnCancel, 'Отмена');
 cxSetResourceString(@sdxBtnClose, 'Закрыть');
 cxSetResourceString(@sdxBtnColor, 'Цвет...');
 cxSetResourceString(@sdxBtnCopy, '&Копировать...');
 cxSetResourceString(@sdxBtnDefault, '&По умолчанию..');
 cxSetResourceString(@sdxBtnDefinePrintStyles, '&Определить стили...');
 cxSetResourceString(@sdxBtnDelete, '&Удалить...');
 cxSetResourceString(@sdxBtnDescription, '&Описание...');
 cxSetResourceString(@sdxBtnDesign, 'Создать...');
 cxSetResourceString(@sdxBtnEdit, 'Редактировать...');
 cxSetResourceString(@sdxBtnFont, 'Шрифт...');
 cxSetResourceString(@sdxBtnHeaderBackground, '&Фон');
 cxSetResourceString(@sdxBtnHeaderFont, '&Шрифт...');
 cxSetResourceString(@sdxBtnMoreColors, '&Еще цвета...');
 cxSetResourceString(@sdxBtnNo, '&Нет');
 cxSetResourceString(@sdxBtnOptions, '&Опции...');
 cxSetResourceString(@sdxBtnPageSetup, 'Настройки страницы...');
 cxSetResourceString(@sdxBtnPreview, 'Предпросмотр...');
 cxSetResourceString(@sdxBtnPrint, 'Печатать...');
 cxSetResourceString(@sdxBtnPrintPreview, 'Предварительный просмотр...');
 cxSetResourceString(@sdxBtnProperties, 'Свойства...');
 cxSetResourceString(@sdxBtnRename, '&Переименовать...');
 cxSetResourceString(@sdxBtnReset, '&Сброс настроек');
 cxSetResourceString(@sdxBtnRestoreDefaults, '&Восстановить настройки по умолчанию');
 cxSetResourceString(@sdxBtnSaveAs, 'Сохранить как...');
 cxSetResourceString(@sdxBtnTextureClear, 'Очистить');
 cxSetResourceString(@sdxBtnYes, '&Да');
 cxSetResourceString(@sdxButtons, 'Кнопки');
 cxSetResourceString(@sdxBytes, 'Байт');
 cxSetResourceString(@sdxCancel, 'Отмена');
 cxSetResourceString(@sdxCaption, '&Название:');
 cxSetResourceString(@sdxContinuedMessage, 'Непрерывный');
 cxSetResourceString(@sdxCopy, '&Копировать');
 cxSetResourceString(@sdxDepth, '&Глубина:');
 cxSetResourceString(@sdxDescription, '&Описание');
 cxSetResourceString(@sdxDetails, '&Детали');
 cxSetResourceString(@sdxEnable, '&Включить');
 cxSetResourceString(@sdxFilterBar, '&Панель фильтрации');
 cxSetResourceString(@sdxFiterFields, '&Поля фильтрации');
 cxSetResourceString(@sdxFitTo, '&Уместить в:');
 cxSetResourceString(@sdxFont, 'Шрифт');
 cxSetResourceString(@sdxFontColor, 'Цвет шрифта');
 cxSetResourceString(@sdxFonts, 'Шрифты');
 cxSetResourceString(@sdxFontStyleItalic, 'Курсив');
 cxSetResourceString(@sdxFourPages, '4 страницы');
 cxSetResourceString(@sdxFSPCaption, 'Предпросмотр картинки');
 cxSetResourceString(@sdxHeight, 'Высота');
 cxSetResourceString(@sdxHFFunctionHintPageNumber, 'Номер страницы');
 cxSetResourceString(@sdxHFFunctionNamePageNumber, 'Номер страницы');
 cxSetResourceString(@sdxHintActivePage, 'Активная страница');
 cxSetResourceString(@sdxHintFileDesign, 'Сконфигурировать отчет');
 cxSetResourceString(@sdxHintFileExit, 'Закрыть');
 cxSetResourceString(@sdxHintFilePageSetup, 'Настройка страницы');
 cxSetResourceString(@sdxHintFilePrint, 'Печать');
 cxSetResourceString(@sdxHintFilePrintDialog, 'Печатать...');
 cxSetResourceString(@sdxHintFormatPageBackground, 'Фон');
 cxSetResourceString(@sdxHintFormatShrinkToPage, 'Уместить на странице');
 cxSetResourceString(@sdxHintGotoPageFirst, 'На первую страницу...');
 cxSetResourceString(@sdxHintGotoPageLast, 'На последнюю страницу...');
 cxSetResourceString(@sdxHintGotoPageNext, 'На следующую страницу...');
 cxSetResourceString(@sdxHintGotoPagePrev, 'На предыдущую страницу...');
 cxSetResourceString(@sdxHintHelpAbout, 'Сведения...');
 cxSetResourceString(@sdxHintToolsOptions, 'Опции');
 cxSetResourceString(@sdxHintViewHFClose, 'Закрыть');
 cxSetResourceString(@sdxHintViewLargeButtons, 'Большие кнопки');
 cxSetResourceString(@sdxHintViewZoom, 'Увеличение');
 cxSetResourceString(@sdxHintZoomFourPages, '4 страницы');
 cxSetResourceString(@sdxHintZoomMultiplyPages, 'Несколько страниц');
 cxSetResourceString(@sdxHintZoomPageWidth, 'Растянуть по ширине страницы');
 cxSetResourceString(@sdxHintZoomPercent100, 'Масштаб 100%');
 cxSetResourceString(@sdxHintZoomTwoPages, 'по 2 страницы');
 cxSetResourceString(@sdxHintZoomWholePage, 'Станица целиком');
 cxSetResourceString(@sdxHintZoomWidenToSourceWidth, 'Все страницы');
 cxSetResourceString(@sdxHorizontalFillPattern, 'Горизонтальный');
 cxSetResourceString(@sdxItemName, 'Имя');
 cxSetResourceString(@sdxLandscape, '&Альбомная');
 cxSetResourceString(@sdxLeft, '&Слева:');
 cxSetResourceString(@sdxLeftMargin, 'Левый отступ');
 cxSetResourceString(@sdxLevelCaption, '&Название');
 cxSetResourceString(@sdxManufacturerNameColumnCaption, 'Имя');
 cxSetResourceString(@sdxMargins, '&Поля:');
 cxSetResourceString(@sdxMenuActivePage, '&Текущая страница:');
 cxSetResourceString(@sdxMenuEdit, '&Редактировать');
 cxSetResourceString(@sdxMenuEditCopy, '&Копировать');
 cxSetResourceString(@sdxMenuEditCut, 'Вырезать');
 cxSetResourceString(@sdxMenuEditDelete, '&Удалить');
 cxSetResourceString(@sdxMenuEditFind, '&Найти...');
 cxSetResourceString(@sdxMenuEditPaste, '&Вставить из буфера');
 cxSetResourceString(@sdxMenuEditReplace, '&Заменить...');
 cxSetResourceString(@sdxMenuExplorerDelete, '&Удалить...');
 cxSetResourceString(@sdxMenuExplorerProperties, '&Свойства...');
 cxSetResourceString(@sdxMenuFile, '&Файл');
 cxSetResourceString(@sdxMenuFileExit, '&Закрыть');
 cxSetResourceString(@sdxMenuFileLoad, '&Загрузить');
 cxSetResourceString(@sdxMenuFilePageSetup, 'Настройка страницы...');
 cxSetResourceString(@sdxMenuFilePrint, '&Печатать...');
 cxSetResourceString(@sdxMenuFileSave, '&Сохранить');
 cxSetResourceString(@sdxMenuFileSaveAs, 'Сохранить как...');
 cxSetResourceString(@sdxMenuFormatPageNumbering, 'Нумерация страниц...');
 cxSetResourceString(@sdxMenuFormatShrinkToPage, '&Уместить на страницу');
 cxSetResourceString(@sdxMenuGotoPage, 'Переход...');
 cxSetResourceString(@sdxMenuGotoPageFirst, '&Первая страница');
 cxSetResourceString(@sdxMenuGotoPageLast, '&Последняя страница');
 cxSetResourceString(@sdxMenuGotoPageNext, '&Следующая страница');
 cxSetResourceString(@sdxMenuGotoPagePrev, '&Предыдущая страница');
 cxSetResourceString(@sdxMenuInsert, '&Вставить');
 cxSetResourceString(@sdxMenuInsertDate, '&Дата');
 cxSetResourceString(@sdxMenuInsertPageNumber, '&Номер страницы');
 cxSetResourceString(@sdxMenuInsertTime, '&Время');
 cxSetResourceString(@sdxMenuInsertTotalPages, '&Число страниц');
 cxSetResourceString(@sdxMenuInsertUserName, '&Имя пользователя');
 cxSetResourceString(@sdxMenuLoad, '&Загрузить...');
 cxSetResourceString(@sdxMenuPages, '&Страницы');
 cxSetResourceString(@sdxMenuPreview, 'Предпросмотр...');
 cxSetResourceString(@sdxMenuThumbnailsLarge, '&Крупные превьюшки');
 cxSetResourceString(@sdxMenuThumbnailsSmall, '&Мелкие превьюшки');
 cxSetResourceString(@sdxMenuTools, '&Инструменты');
 cxSetResourceString(@sdxMenuToolsCustomize, '&Настроить...');
 cxSetResourceString(@sdxMenuToolsOptions, '&Опции...');
 cxSetResourceString(@sdxMenuView, 'Вид');
 cxSetResourceString(@sdxMenuViewFlatToolBarButtons, '&Плоские кнопки в меню');
 cxSetResourceString(@sdxMenuViewHFClose, '&Закрыть');
 cxSetResourceString(@sdxMenuViewMargins, '&Поля');
 cxSetResourceString(@sdxMenuViewPagesStatusBar, '&Строка состояния');
 cxSetResourceString(@sdxMenuViewToolBars, '&Панели инструментов');
 cxSetResourceString(@sdxMenuZoom, '&Масштаб');
 cxSetResourceString(@sdxMenuZoomFourPages, 'По 4 страницы');
 cxSetResourceString(@sdxMenuZoomSetup, '&Настройка...');
 cxSetResourceString(@sdxMenuZoomTwoPages, '&2 страницы');
 cxSetResourceString(@sdxMenuZoomWholePage, 'Станица целиком');
 cxSetResourceString(@sdxMenuZoomWidenToSourceWidth, 'Все страницы');
 cxSetResourceString(@sdxMode, '&Режим:');
 cxSetResourceString(@sdxNameCaption, 'Имя');
 cxSetResourceString(@sdxOnEveryPage, 'На каждой странице');
 cxSetResourceString(@sdxOptions, 'Опции');
 cxSetResourceString(@sdxOrientation, 'Ориентация');
 cxSetResourceString(@sdxPage, '&Страница');
 cxSetResourceString(@sdxPageBackground, 'Фон страницы');
 cxSetResourceString(@sdxPageNumbering, 'Нумерация страниц');
 cxSetResourceString(@sdxPages, 'стр.');
 cxSetResourceString(@sdxPageSetupCaption, 'Настройка страницы');
 cxSetResourceString(@sdxPageWidth, 'Ширина страницы');
 cxSetResourceString(@sdxPagination, 'Разбиение на страницы');
 cxSetResourceString(@sdxPaper, 'Бумага');
 cxSetResourceString(@sdxPaperSize, 'Размер бумаги:');
 cxSetResourceString(@sdxPaperWidth, '&Ширина:');
 cxSetResourceString(@sdxPercentOfNormalSize, '% нормального размера');
 cxSetResourceString(@sdxPNFormatsCaption, 'Формат номеров страниц');
 cxSetResourceString(@sdxPopupMenuFlatButtons, '&Плоские кнопки');
 cxSetResourceString(@sdxPopupMenuLargeButtons, '&Крупные кнопки');
 cxSetResourceString(@sdxPosition, '&Позиция');
 cxSetResourceString(@sdxPositioning, 'Размещение');
 cxSetResourceString(@sdxPredefinedFunctions, 'Предопределенные функции');
 cxSetResourceString(@sdxPreferenceDlgCaption, 'Опции');
 cxSetResourceString(@sdxPreferenceDlgFlatBtns, '&Плоские кнопки в меню');
 cxSetResourceString(@sdxPreferenceDlgMargins, '&Поля');
 cxSetResourceString(@sdxPressEscToCancel, 'Нажмите Esc для отмены');
 cxSetResourceString(@sdxPrintDialogAllPages, 'Все');
 cxSetResourceString(@sdxPrintDialogCaption, 'Печать');
 cxSetResourceString(@sdxPrintDialogPageRange, 'Диапазон страниц');
 cxSetResourceString(@sdxPrintDialogPages, '&Страницы:');
 cxSetResourceString(@sdxPrintDialogPrinter, 'Принтер');
 cxSetResourceString(@sdxPrintDialogPSPaused, 'Приостановлено');
 cxSetResourceString(@sdxPrintDialogSelection, '&Выбор');
 cxSetResourceString(@sdxPrintedBy, 'Кем отечатано:');
 cxSetResourceString(@sdxPrintOrder, 'Порядок печати');
 cxSetResourceString(@sdxPrintPreview, 'Предпросмотр');
 cxSetResourceString(@sdxPrintRangeEnd, '&Конец:');
 cxSetResourceString(@sdxPrintRanges, 'Печатать диапазоны');
 cxSetResourceString(@sdxPrintStyleWeeklyArrangeL2R, 'Слева направо');
 cxSetResourceString(@sdxPrintStyleWeeklyArrangeT2B, 'Сверху вниз');
 cxSetResourceString(@sdxPrintStyleWeeklyDaysLayoutTC, '2 колонки');
 cxSetResourceString(@sdxProperties, '&Свойства');
 cxSetResourceString(@sdxReverseOnEvenPages, '&Изменит на четных страницах');
 cxSetResourceString(@sdxRight, 'Справа:');
 cxSetResourceString(@sdxRightMargin, 'Правое поле');
 cxSetResourceString(@sdxRows, '&Строки');
 cxSetResourceString(@sdxSave, '&Сохранить...');
 cxSetResourceString(@sdxScaling, '&Масштабирование');
 cxSetResourceString(@sdxSelectAll, '&Выбрать все');
 cxSetResourceString(@sdxSize, 'Размер');
 cxSetResourceString(@sdxSizes, 'Размеры');
 cxSetResourceString(@sdxTextAlignCenter, 'По центру');
 cxSetResourceString(@sdxTextAlignLeft, 'По левому краю');
 cxSetResourceString(@sdxTextAlignRight, 'По правому краю');
 cxSetResourceString(@sdxTextAlignTop, 'По верхнему краю');
 cxSetResourceString(@sdxTextAlignVCenter, 'По центру');
 cxSetResourceString(@sdxTextAlignVert, '&Вертикально');
 cxSetResourceString(@sdxTitleModeOnEveryTopPage, 'На каждой верхней странице');
 cxSetResourceString(@sdxTitleModeOnFirstPage, 'На первой странице');
 cxSetResourceString(@sdxTLColumnName, 'Имя');
 cxSetResourceString(@sdxTop, '&Сверху:');
 cxSetResourceString(@sdxTopMargin, 'Верхнее поле');
 cxSetResourceString(@sdxTotal, 'Всего');
 cxSetResourceString(@sdxTransparent, '&Прозрачный');
 cxSetResourceString(@sdxTwoPages, '2 страницы');
 cxSetResourceString(@sdxUnitsCentimeters, 'см');
 cxSetResourceString(@sdxUnitsInchesName, 'Дюймы');
 cxSetResourceString(@sdxUnitsMillimeters, 'мм');
 cxSetResourceString(@sdxVertAlignment, 'Выравнивание по вертикали');
 cxSetResourceString(@sdxVertically, '&Вертикально');
 cxSetResourceString(@sdxVertLines, '&Вертикальные линии');
 cxSetResourceString(@sdxViewTab, 'Вид');
 cxSetResourceString(@sdxVisible, '&Видимый');
 cxSetResourceString(@sdxWholePage, 'Станица целиком');
 cxSetResourceString(@sdxWidenToSourceWidth, 'Все страницы');
 cxSetResourceString(@sdxWidth, 'Ширина');
 cxSetResourceString(@sdxZoomDlgCaption, 'Увеличение');
 cxSetResourceString(@sdxZoomDlgFourPages, 'По 4 страницы');
 cxSetResourceString(@sdxZoomDlgPreview, 'Предпросмотр');
 cxSetResourceString(@sdxZoomDlgTwoPages, '&2 страницы');
 cxSetResourceString(@sdxZoomDlgWholePage, 'Станица целиком');
 cxSetResourceString(@sdxZoomDlgZoomTo, 'Масштаб...');

end.

